const mongoose = require('mongoose');
const Schema = mongoose.Schema;

const TV = new Schema({
  adult: { type: Boolean },
  backdrop_path: { type: String },
  created_by: { type: Array },
  episode_run_time: { type: Array },
  first_air_date: { type: String },
  genres: { type: Array },
  homepage: { type: String },
  id: { type: Number },
  in_production: { type: Boolean },
  languages: { type: Array },
  last_air_date: { type: String },
  last_episode_to_air: { type: Object },
  name: { type: String },
  title: { type: String },
  next_episode_to_air: { type: Object },
  networks: { type: Array },
  number_of_episodes: { type: Number },
  number_of_seasons: { type: Number },
  origin_country: { type: Array },
  original_language: { type: String },
  original_title: { type: String },
  original_name: { type: String },
  overview: { type: String },
  popularity: { type: Number },
  poster_path: { type: String },
  production_companies: { type: Array },
  production_countries: { type: Array },
  seasons: { type: Array },
  spoken_languages: { type: Array },
  status: { type: String },
  tagline: { type: String },
  type: { type: String },
  vote_average: { type: Number },
  vote_count: { type: Number },
  videos: { type: Object },
  credits: { type: Object },
  // createdAt: { type: Date, default: Date.now },
  // updatedAt: { type: Date, default: Date.now },
});

module.exports = mongoose.model('TV', TV);
